version: "3.9"

services:

  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15
    container_name: rag-postgres
    restart: always
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: rag-nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  pgdata:
